name: 
on: [push, pull_request, create, delete]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 'stable'
      - run: npm install

      - name: NPM test
      - run: npm test

      - name: Lint
      - run: npm run lint

      - name: Spell-check
      - run: npm run spellcheck