name: 
on: [push, pull_request, create, delete]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 'stable'
      - run: npm install
      - run: npm test
      - run: npm run lint
      - run: npm run spellcheck